# Written by the Quickshell shell (kde-quickshell): its theme "{{ title }}".
palette = 0={{ terminal0 }}
palette = 1={{ terminal1 }}
palette = 2={{ terminal2 }}
palette = 3={{ terminal3 }}
palette = 4={{ terminal4 }}
palette = 5={{ terminal5 }}
palette = 6={{ terminal6 }}
palette = 7={{ terminal7 }}
palette = 8={{ terminal8 }}
palette = 9={{ terminal9 }}
palette = 10={{ terminal10 }}
palette = 11={{ terminal11 }}
palette = 12={{ terminal12 }}
palette = 13={{ terminal13 }}
palette = 14={{ terminal14 }}
palette = 15={{ terminal15 }}
background = {{ terminalBackground }}
foreground = {{ terminalForeground }}
cursor-color = {{ terminalCursor }}
cursor-text = {{ terminalBackground }}
selection-background = {{ terminalSelection }}
selection-foreground = {{ terminalForeground }}
